### ISSUE TITLE
Cascade softRemove on relations

### ISSUE THREAD

**Issue by Abdizriel** [iWinston/typeorm-plus#30]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I have an issue with a cascade softRemove on relations. This is the entry for a **Client** table

```ts
  @Field(_ => [Patient])
  @OneToMany(
    _ => Patient,
    patient => patient.owner,
    { lazy: true, cascade: true  },
  )
  public patients: Lazy<Patient[]>
```

So when i do softRemove on a client entry it should do softRemove on all patients. This is how I do softRemove on my service:

```ts
  async removeById(id: string) {
    const client = await this.getById(id)
    return this.clientRepository.softRemove(client)
  }
```

It soft removed a client correctly however all patients where client is the owner are not soft removed. Could you point where the error is? I have even tried this but it also didn't worked:

```ts
  @Field(_ => [Patient])
  @OneToMany(
    _ => Patient,
    patient => patient.owner,
    { lazy: true, cascade: true, onDelete: 'CASCADE'  },
  )
  public patients: Lazy<Patient[]>
```

or even on the Patient table which also didn't worked

```ts
  @Field(_ => Client)
  @ManyToOne(_ => Client, { lazy: true, cascade: true })
  public owner: Lazy<Client>
```

**Comment by iWinston** [comment]
Hi, can you show me the code of  `this.getById()` ?
The `softRemove` only works when you pull the patients with the owner at the same time.

I am sorry for missing the notify.

**Comment by ruslanguns** [comment]
@iWinston  Is cascade supported in Typeorm or only in Typeorm+? I mentioned it at : https://github.com/typeorm/typeorm/pull/5034#issuecomment-621398924

**Comment by Abdizriel** [comment]
@iWinston this is the code fot `this.getById()`

```ts
async getById(id: string): Promise<Client> {
    return this.clientRepository.findOne({ id, tenant: this.tenant })
  }
```

**Comment by ruslanguns** [comment]
@Abdizriel  how did you solve the circular dependency by using cascade: true in both the entity and the child entity? and what does @Type decorator does?

**Comment by Abdizriel** [comment]
@ruslanguns I had to remove one cascade true and I did it from a child (Patient)

**Comment by iWinston** [comment]
@Abdizriel  Maybe you can try this:
```
async getById(id: string): Promise<Client> {
    return this.clientRepository.findOne({
        where: { id, tenant: this.tenant },
        relations: ['patients']
     })
  }
```

**Comment by ruslanguns** [comment]
@iWinston How can I find softdeleted users?

.... I just edited my comment at https://github.com/typeorm/typeorm/pull/5034#issuecomment-621398924

**Comment by Abdizriel** [comment]
@iWinston Yeah, that one worked however then in case of softRemove I have to add everywhere relations since it doesn't work with lazy loading.

**Comment by ruslanguns** [comment]
Nevermind, just discovered it by myself using { withDeleted: true } .... thank you @iWinston for this great feature!!

**Comment by iWinston** [comment]
@Abdizriel Maybe you can try eager relations if you want it to be loaded automatically.

**Comment by Abdizriel** [comment]
@iWinston Sorry for late reply, it worked as you said! Thank you very much for help with this. One last question - How I can include soft deleted entry from relations to a response from repository? Since I can do it for a main entity `{ withDeleted: true }`

**Comment by iWinston** [comment]
@Abdizriel  It will always include soft deleted entry from relations to a response from repository by default.
The default global condition of non-deleted is just applied to the  main entity.
