### ISSUE TITLE
Getting deleted posts when use relation.

### ISSUE THREAD

**Issue by matheusmorett2** [iWinston/typeorm-plus#33]
**Issue type:**

[x] question
[x] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I'm running this code and getting the reponse with deleted posts: 

Find

```
const userRepository = await this.userRepository.findOne({
      where: {
        id: id,
      },
      relations: ['posts'],
    });
```

Response

```
{
  "id": 4,
  "name": "Michael Jordan",
  "createdAt": "2020-09-26T23:07:13.000Z",
  "updatedAt": "2020-09-26T23:07:13.000Z",
  "deletedAt": null,
  "posts": [
    {
      "id": 5,
      "name": "Post One",
      "createdAt": "2020-09-26T23:07:45.000Z",
      "updatedAt": "2020-09-26T23:08:27.000Z",
      "deletedAt": "2020-09-26T23:08:27.000Z"
    },
    {
      "id": 6,
      "name": "Post Two",
      "createdAt": "2020-09-26T23:14:09.000Z",
      "updatedAt": "2020-09-26T23:14:20.000Z",
      "deletedAt": null,
    }
  ]
}
```

How can i filter to get only not deleted posts?

**Comment by iWinston** [comment]
The global "non-deleted" condition only applies to the main alias.
Maybe you can use the query builder to get only not deleted posts.

**Comment by Audrey-Ann** [comment]
@iWinston Hello there! Thank you very much for this package! 

I am facing the same issue and was wondering if loading an entity with its relation that may be soft removed was only possible via a query builder ? 

Thank you very much in advance!

**Comment by iWinston** [comment]
Be default you will get all the entity no matter their relation have been soft removed or not.
if you want to load an entity with its relation that may be soft removed, you can just use a repository or a query builder.
