### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by ygorlazaro** [iWinston/typeorm-plus#4]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[x] `mysql` / `mariadb`
[ ] `oracle`
[ ] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

I loved this initiative! I had some issues with TypeORM maintainer, as seen at https://github.com/typeorm/typeorm/issues/4686.

I've started a fork seeking to fix some of the troubles I noted there, but it's kind sad to be alone. Now that I have found you, would you mind if I participate here? Let's join forces to grow this project, what do you thing?

I already have a project in production, circa 4k-6k simultaneous access sometimes during a day. I am willing to replace `typeorm` by `typeorm-plus` there, could be a showcase.

@iWinston congrats

**Comment by victoraliss0n** [comment]
+1

**Comment by iWinston** [comment]
Thank you for your love of TypeORM+ @ygorlazaro @victoraliss0n.

I have forked the TypeORM 0.2.19, and I am recommitting my code and adding more tests for TypeORM+ now. 

I think it will be fine for you to replace TypeORM by TypeORM+ after I finished it in the next week, as I'm busy participating in a hackathon this weekend. 

This repository is intended to get advice from the developers who want some functionalities faster. When the functionalities become mature, I would like to make some PRs or some plugins for TypeORM. And I will keep updating this repository before this.

**Comment by ygorlazaro** [comment]
Great, @iWinston ,

I saw an old PR on TypeORM's original repository, witch adds soft delete suport in cascade. What do you think add this here?

**Comment by iWinston** [comment]
Did you mean this PR: https://github.com/typeorm/typeorm/pull/1192?

We have started a conversation here. https://github.com/iWinston/typeorm-plus/issues/2

**Comment by iWinston** [comment]
Hi, I am glad to tell you the release 0.0.55 is available.

I have refactored all the code of TypeORM+ and added more tests for it. And the Cascading Soft Deletes is supported now.

**Comment by artoodeeto** [comment]
@iWinston @ygorlazaro ey dudes are you still working on this one? lets work on this one. let me help. We could evolve this. Ive been trying to use typeorm on my personal project but im hitting issues.

**Comment by iWinston** [comment]
@artoodeeto Hi, I am still working on this repo. 

I will keep fixing bugs and adding necessary features.

What're the issues you have found?

**Comment by artoodeeto** [comment]
@iWinston I have a few like when I access a route, just a route for some reason typeorm queries the database. 

example: 

```
// uncomment and test this route, because for some magical reason its trying to
  // query a user model even though theres no code accessing the module. crazy
  // @Get('test')
  // private async test(req: Request, res: Response) {
  //   console.log('asdfadsf');
  //   res.json({
  //     samp: 'asdf'
  //   });
  // }
```

this route will access the data for some reason.  I talk to the owner of the package that im using for express typescript (overnightjs) and he thinks its from typeorm, been debugging this for 3days now and still cant figure it out. Error says No Entity ` select User from User where parameters [test]` heres a [repo](https://github.com/artoodeeto/ggpo-server/blob/master/src/controllers/users_controller.ts) if you want to test it out. im just starting so theres no readme for now but you can just install the packages and do `npm run dev` and uncomment the route from users_controllers im using insomia for testing my API and this [issue](https://github.com/typeorm/typeorm/issues/5188) that I posted on typeorm.

Also let me know how can I help on this. thank you sir.

**Comment by iWinston** [comment]
@artoodeeto 
I have replied to your issue https://github.com/typeorm/typeorm/issues/5188 .

And another issue you mentioned may cause by the route 'test' is shadowed by the route ':id'.
```
// When testing your API, this route works
  @Get(':id')
  private async getSingleUser(req: Request, res: Response) {
    const { id } = req.params;
    const { username, email } = await User.findOneOrFail(id);
    try {
      res.json({
        meta: {},
        payload: {
          username,
          email
        }
      });
    } catch (error) {
      res.json({
        errorMsg: error
      });
    }
  }

  // uncomment and test this route, because for some magical reason its trying to
  // query a user model even though theres no code accessing the module. crazy
  // @Get('test')
  // private async test(req: Request, res: Response) {
  //   console.log('asdfadsf');
  //   res.json({
  //     samp: 'asdf'
  //   });
  // }
```

This repository is intended to get advice from the developers who want some functionalities faster. 

Maybe you can try to use TypeORM+ in your personal project if you need the features that TypeORM+ provides? 

It will be greatly helpful to give me some advice about this.

**Comment by artoodeeto** [comment]
@iWinston thank you so much for this. I appreciate the help. finally! I didnt notice that. I got so curious that I wanted to redo everything. thank you! Im planning to use this now. thank you thank you.

**Comment by iWinston** [comment]
@artoodeeto You're welcome. You can use ':id(\\\\d+)' to avoid this problem.
