### ISSUE TITLE
Implement boolean soft deletes?

### ISSUE THREAD

**Issue by henry-young** [iWinston/typeorm-plus#5]
**Issue type:**

[ ] question
[ ] bug report
[x] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

I'd like to be able to use a decorator similar to `@DeleteDateColumn` (e.g. `@DeleteColumn`) which provides the same soft delete functionality when querying entities, but implemented with  `boolean` type instead of `Date`.

This would be useful in the case where the typescript code doesn't manage the schema of the database, and the managing system uses booleans to implement soft deletes (e.g. Hibernate ORM in Java).

**Comment by iWinston** [comment]
This is really a dilemma. Some ORMs(e.g. GORM in Golang and Eloquent in Laravel) use the `@DeleteDateColumn`, and some use the `DeleteColumn`.

Sorry, I don't think it's necessary to support both in one ORM. And I consider that it's beneficial to record 
the delete time.

**Comment by henry-young** [comment]
No problems, I understand that it is beneficial to record the delete time and the overhead in supporting both mechanisms. Unfortunately it doesn't help in my particular case. 
Potentially I could use a 'default' scope to achieve a similar result?

**Comment by iWinston** [comment]
Yes, you can set the `default` scope like this:
```
export class CommonEntity {

    static scope = {
      'default': {
        deleted: false
      }
    }

}
```

Then the scope will apply to your `Repository` and `QueryBuilder`. 

But you still need to update this column by calling `update` rather than `softDelete`.

Maybe you can use a custom `Repository` to build your soft deletes.

**Comment by CaioFilus** [comment]
> 
Hii @iWinston , just a complement to your response, i think is necessary to add support to both DeleteColumn types, in new projects its Ok dont need both, but i am working in legacy database who use boolean as deleteFlag, and i cant change this database, and ORM does not give a function to this, so i have to implment it manually in querys
