### ISSUE TITLE
Preserving TypeORM whitespace rules for simpler rebasing

### ISSUE THREAD

**Issue by goldcaddy77** [iWinston/typeorm-plus#6]
**Issue type:**

[x] question
[ ] bug report
[ ] feature request
[ ] documentation issue

**Database system/driver:**

[ ] `cordova`
[ ] `mongodb`
[ ] `mssql`
[ ] `mysql` / `mariadb`
[ ] `oracle`
[x] `postgres`
[ ] `cockroachdb`
[ ] `sqlite`
[ ] `sqljs`
[ ] `react-native`
[ ] `expo`

**TypeORM version:**

[x] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Steps to reproduce or a small repository showing the problem:**

Hey, love the project - been looking for soft deletes in TypeORM for a while!  

I noticed that you're not preserving the whitespace rules that TypeORM uses so your diffs are really large as you make your customizations. Given you'll need to continuously pull in the latest from TypeORM , does It make sense to obey their whitespace rules by shutting auto-formatters off so that rebasing will be easier?

Also, are you planning on maintaining this project long-term?

Thanks!

**Comment by iWinston** [comment]
Hello, I'm sorry that I forgot to disable the auto-format at the beginning of this repository.

And as I refactored this repository so many times, the commit history seems to be a bit messy.

So I have forked the TypeORM 0.2.19, and I am recommitting my code and adding more tests for TypeORM+ now.

I will keep updating this repository until it becomes a PR or there's a better way with the same features.

**Comment by goldcaddy77** [comment]
No worries at all. If you're planning on keeping this around for a while, you could always start over by remaking the changes that you find by doing a diff of your head and TypeORM's head ignoring whitespace only differences.

Hoping this becomes a PR soon though :)

**Comment by iWinston** [comment]
Thank you for your advice @goldcaddy77

**Comment by iWinston** [comment]
Hi, I am glad to tell you the release 0.0.55 is available.

And I have refactored and recommitted all the code of TypeORM+.

**Comment by goldcaddy77** [comment]
Very cool - thanks for the update
